[package]
name = "ltxprs"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "*"
nom_locate = "*"
clap = {version = "*", features = ["derive"] }
